service: build-notifier-auth

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  timeout: 15 # Avoiding cold start timeouts.
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  tracing: 
    apiGateway: true
    lambda: true
  deploymentBucket: build-notifier-auth-deployments
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
        - "xray:GetSamplingRules"
        - "xray:GetSamplingTargets"
        - "xray:GetSamplingStatisticSummaries"
      Resource: "*"
  environment:
    STAGE: ${self:provider.stage}
    BITBUCKET_CLIENT_ID: ${env:BITBUCKET_CLIENT_ID}
    BITBUCKET_CLIENT_SECRET: ${env:BITBUCKET_CLIENT_SECRET}
    GITHUB_CLIENT_ID: ${env:GITHUB_CLIENT_ID}
    GITHUB_CLIENT_SECRET: ${env:GITHUB_CLIENT_SECRET}
    HOST: ${env:HOST}
    NODE_ENV: ${env:NODE_ENV, 'development'}
    LOG_LEVEL: ${env:LOG_LEVEL, 'info'}

package:
  exclude:
    - 'src/**/*'
    - 'tsconfig.json'
    - '.env'
    - '.env.*'

functions:
  main:
    handler: dist/index.handler
    events:
      - http: ANY {proxy+}


plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies
